CAPI=2:

name : cr1901:amaranth:uart:0

filesets:
  # No special way to expose a Python core to be used by Amaranth in CAPI,
  # so abuse filesets.
  module:
    file_type: pythonModule
    files:
      - uart

# This is unused at the moment/subject to change. At present causes a
# PermissionsError trying to read a directory (uart).
# targets:
#   default:
#     filesets: [module]

generators:
  amaranth_uart_gen:
    interpreter: python3
    command: gen_entry.py
    usage: |
      Generate a simple UART.
